### PR TITLE
When checking for existing wrangler install, match wrangler version even if multiline output

### PR DESCRIPTION
**Pull request by acusti**
implements #277

i don’t know how to test or verify this, but in case it’s helpful, here’s my proposed solution (assuming my hypothesis from #277 is correct).

i think this will also fix the issue documented here: https://github.com/cloudflare/wrangler-action/issues/199#issuecomment-2188863592

### CODE REVIEW

**Review by austinorth — APPROVED** [review]
Looks good to me!

**Comment by austinorth** [comment]
@Maximo-Guk Can we get this merged please?

**Review by threepointone — APPROVED** [review]

**Comment by Maximo-Guk** [comment]
Hi @acusti this looks good to me, thank you! Could you add a changeset please? 

For [reference](https://github.com/cloudflare/workers-sdk/blob/main/CONTRIBUTING.md#changesets)

**Comment by acusti** [comment]
@Maximo-Guk done!

**Review by Maximo-Guk — APPROVED** [review]
Thank you!

**Pull request merged**
