### PR TITLE
Support many package managers

### LINKED ISSUE #156: v3 does not work with other package managers
Currently getting the following error thrown ` npm ERR! Cannot read properties of null (reading 'matches')` in [https://github.com/zanechua/comment-worker/actions/runs/5857501953/job/15879483256 ](https://github.com/zanechua/comment-worker/actions/runs/5857501953/job/15879483256 )

Seems to be an [incompatibility](https://github.com/npm/cli/issues/4367#issuecomment-1674381286) since I am using `pnpm` instead of `npm`?

Can we have support for making use of other package managers to install wrangler other than `npm` ?

### PR DESCRIPTION
**Pull request by nix6839**
We must choose whether to install the package manager in this action or leave it up to the user.

Maybe fix #156

### CODE REVIEW

**Review by JacobMGEvans — APPROVED** [review]

**Review by JacobMGEvans — CHANGES_REQUESTED** [review]
Could you please add a `changeset` by using `npx changeset`

**Comment by JacobMGEvans** [comment]
My change will also allow the CI to run.

**Comment by JacobMGEvans** [comment]
This test in the branch I made to run CI (with my permissions for GH Auth Token) is showing the Environments E2E tests are failing now. 

https://github.com/cloudflare/wrangler-action/actions/runs/6225473338/job/16895989165

**Comment by nix6839** [comment]
@JacobMGEvans Can you please allow CI again? I want to see error message.

**Comment by nix6839** [comment]
Is there anything I can do about it now?

**Comment by JacobMGEvans** [comment]
> Is there anything I can do about it now?

Figure out why you changes caused the Environment E2E's to fail, the action can be tested/developed locally with https://github.com/nektos/act

If you don't I am sure someone will pick up the PR, if not me.

**Comment by nix6839** [comment]
@JacobMGEvans I fix it.

P.S.  `act` is awesome! Thanks for letting me know about that!

**Review by JacobMGEvans — APPROVED** [review]
I think this is a great initial implementation and covers some of the major package managers in the JS/TS ecosystem! Thanks for the hard work 😄

**Pull request merged**
